name: Test

on:
  # Push on main and release tags
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  # PR
  pull_request:
    branches:
      - 'main'

  # Manual trigger
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Test
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"

          if [ "$GITHUB_EVENT_NAME" == 'workflow_dispatch' ] && [ "$GITHUB_REF_TYPE" != 'tag' ]; then
            echo "It's not a tag"
          else
            echo "It's a tag"
          fi
